### ISSUE TITLE
"DROP IF EXISTS" does not work

### ISSUE THREAD

**Issue by mikeyc7m** [oddnoc/silverstripe-artefactcleaner#10]
I found that columns and indexes could not be processed, the SQL failed because of the IF EXISTS clause. Apparently the syntax is not supported in MySQL.

Simple fix was to remove the clause and it worked fine.

**Comment by oddnoc** [comment]
Can you provide details of your MySQL version?

**Comment by mikeyc7m** [comment]
I'm using 5.6.17

**Comment by oddnoc** [comment]
Fixed in 4.0.2. Thanks!
