### ISSUE TITLE
ERROR [User Error]: Attempted to connect to non-existing database "tmpdb"

### ISSUE THREAD

**Issue by peavers** [oddnoc/silverstripe-artefactcleaner#2]
Latest build is throwing:
`ERROR [User Error]: Attempted to connect to non-existing database "tmpdb"`

When trying to run across a 3.2.1 build

**Comment by oddnoc** [comment]
Thanks for the report.

It looks like the 'tmpdb' database is unneeded. But your DB user will still need enough privileges to create a temporary DB. I usually use this in a dev environment where the DB root user is in use.

See the feature/2-tmpdb branch.
